apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
  - name: citybaseinc-jenkins-push-bot-pull-secret
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  containers:
  - name: docker
    image: docker:17.12
    command:
    - cat
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      # Socket must exist or volume will fail
      type: Socket
